version: '3.8'
services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: siddheshdevops/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
  
  vpromq01:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  
  vproapp:
    build: 
      context: ./Docker-files/app
    image: siddheshdevops/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"

  vproweb:
    build: 
      context: ./Docker-files/web
    image: siddheshdevops/vprofileweb
    container_name: vproweb
    ports:
      - "8070:80"

volumes:
  vprodbdata: {}
